#!/bin/sh
CONFIG_BASEDIR=~/.kube
CONFIGS_LIST="kind"
ACTIVE_KUBECONFIG=${KUBECONFIG:-~/.kube/config}
ACTIVE_CONTEXT=$(kubectx -c 2>/dev/null)
KUBECONFIG=
 
cd $CONFIG_BASEDIR
KUBECONFIG=`find ${CONFIGS_LIST} -type f | paste -d : -s -`

export KUBECONFIG
kubectl config view \
  --merge --flatten > ${ACTIVE_KUBECONFIG}
KUBECONFIG=$ACTIVE_KUBECONFIG
[ -n ${ACTIVE_CONTEXT} ] && kubectx ${ACTIVE_CONTEXT} 2>/dev/null
